---
- name: Install systemd files
  template: src=systemd/otp.service dest=/etc/systemd/system/otp-{{item.name }}.service
  with_items: "{{ tile_providers }}"

- name: Start services
  systemd:
    name: "otp-{{ item.name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: "{{ tile_providers }}"

- name: Caddyfile
  ansible.builtin.template:
    src: templates/Caddyfile
    dest: /etc/caddy/otp.caddy
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy
